services:
  budget-app:
    build: . # Ou image: votre-repo/budget:latest
    container_name: budget_app
    # network_mode: host # Désactivé pour permettre le mapping de port
    # Port Externe (8097) : Port Interne (8090)
    ports:
      - "8097:8090"
    environment:
      - ENABLE_BANKING_APP_ID=c2bd280b-383f-4272-9b42-df5410c504cf
    volumes:
      - ./pb_data:/pb/pb_data # Données persistantes
      - ./pb_migrations:/pb/pb_migrations # Migrations de schéma (CRUCIAL)
      - ./pb_public:/pb/pb_public # Fichiers Web (Frontend)
      - ./pb_hooks:/pb/pb_hooks # Scripts JS (Hooks) API
      # - /volume1/docker/budget/pb_data:/pb/pb_data # Exemple Synology absolu
    restart: unless-stopped
