import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/start_app.dart';
import '../../categories/domain/category.dart';
import '../../categories/data/category_repository_impl.dart';

class CategoryController extends StateNotifier<AsyncValue<List<Category>>> {
  final CategoryRepositoryImpl _repository;

  CategoryController(this._repository) : super(const AsyncValue.loading()) {
    loadCategories();
  }

  Future<void> loadCategories() async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() => _repository.getCategories());
  }

  Future<void> addCategory({
    required String name,
    required int iconCodePoint,
    required int colorHex,
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await _repository.createCategory(
        Category(
          id: '', // ID generated by DB
          name: name,
          icon: IconData(iconCodePoint, fontFamily: 'MaterialIcons'),
          color: Color(colorHex),
          isSystem: false,
        ),
      );
      return _repository.getCategories();
    });
  }

  Future<void> deleteCategory(String id) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await _repository.deleteCategory(id);
      return _repository.getCategories();
    });
  }
}

final categoryControllerProvider =
    StateNotifierProvider<CategoryController, AsyncValue<List<Category>>>((
      ref,
    ) {
      final repo =
          ref.watch(categoryRepositoryProvider) as CategoryRepositoryImpl;
      return CategoryController(repo);
    });
